print ("АНКЕТА")
print("ВВЕДИТЕ ВАШЕ ФИО")
otvet1 = input()
print("СКОЛЬКО ВАМ ЛЕТ?")
otvet2 = input()
print("СКОЛЬКО ВЫ ВЕСИТЕ?")
otvet3 = input()
print("ВВЕДИТЕ ВАШЕ МЕСТО ЖИТЕЛЬСТВА")
otvet4 = input()
print("КАКОВ ВАШ РОСТ?")
otvet5 = input()
print("ЕСТЬ ЛИ У ВАС ДОМАШНЕЕ ЖИВОТНОЕ?")
print("БЛАГОДАРИМ ЗА УЧАСТИЕ В АНКЕТИРОВАНИИ")   